name: Build EXE (bundle model + CPU PyTorch)

on:
  push:
    branches:
      - main
      - 'ci/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install CPU-only PyTorch (Windows)
        run: python -m pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision --upgrade
        shell: powershell

      - name: Install dependencies from requirements.txt
        run: python -m pip install -r requirements.txt
        shell: powershell

      - name: Pre-download HF model for offline bundling
        # This downloads the model files into hf_models/resnet50 so we can bundle them.
        run: |
          python tools/prep_model.py --model microsoft/resnet-50 --out hf_models/resnet50
        shell: powershell

      - name: Verify key packages import
        run: |
          python - <<'PY'
          import sys
          pkgs = ["pandas","numpy","transformers","torch","PIL","openpyxl","pyinstaller"]
          missing = []
          for p in pkgs:
              try:
                  __import__(p if p!="PIL" else "PIL")
              except Exception as e:
                  missing.append((p,str(e)))
          if missing:
              print("Missing or failing imports:")
              for m in missing:
                  print(m)
              sys.exit(1)
          else:
              print("All key packages import successfully.")
          PY
        shell: powershell

      - name: Install/upgrade PyInstaller
        run: python -m pip install --upgrade pyinstaller
        shell: powershell

      - name: Build EXE with PyInstaller (collect package data + bundle model)
        # --clean avoids leftover artifacts; --collect-all helps include package data for complex libs
        run: |
          $model_src = "hf_models\resnet50"
          # When bundling data on Windows, PyInstaller expects dest separated by semicolon
          $add_data = "$model_src;$model_src"
          pyinstaller --clean --onefile --icon="artifact.ico" ArchaeologyApp.py `
            --collect-all pandas --collect-all numpy --collect-all transformers --collect-all tokenizers --collect-all PIL `
            --add-data $add_data
        shell: powershell

      - name: Show PyInstaller build warnings (if present)
        if: always()
        run: |
          $warnFile = Join-Path $PWD "build\warnpylib"
          if (Test-Path $warnFile) {
            Write-Host "===== PyInstaller warnpylib ====="
            Get-Content $warnFile -Raw
            Write-Host "===== end warnpylib ====="
          } else {
            Write-Host "No build warnpylib file found."
          }
        shell: powershell

      - name: Run built EXE to capture runtime output
        if: always()
        run: |
          $exe = Join-Path $PWD "dist\ArchaeologyApp.exe"
          if (Test-Path $exe) {
            Write-Host "Running EXE to capture stdout/stderr..."
            & $exe > run.log 2>&1
            Write-Host "Exit code: $LASTEXITCODE"
            Write-Host "===== run.log ====="
            Get-Content run.log -Raw
            Write-Host "===== end run.log ====="
          } else {
            Write-Host "EXE not found at $exe"
            exit 1
          }
        shell: powershell

      - name: Upload build artifacts and logs
        uses: actions/upload-artifact@v4
        with:
          name: built-exe-and-logs
          path: |
            dist/*.exe
            build/
            run.log